name: SDKReleaseJob

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AAR_FILE_PATH: ''
      AAR_FILE_NAME: ''
      TEST_PATH: ''

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: amyu/setup-android@v3
        with:
            sdk-version: 34


      - name: Build AAR
        id: buildAAR
        run: ./gradlew :jchart:clean && ./gradlew :jchart:releaseSDK

      - name: Test ENV value
        run: |
          echo "TEST_PATH = test_path " >> "$GITHUB_ENV"
         

      - name: Find AAR Path
        run: |
          echo "AAR_FILE_PATH =$(find jchart/build/outputs/aar/ -type f -name '*.aar')" >> "$GITHUB_ENV"

      - name: AAR file name
        run: |
          echo "AAR_FILE_NAME =$(basename $AAR_FILE_PATH)" >> "$GITHUB_ENV"

      - name: Test AAR Path
        run: |
          echo "Gradle Task Result: testPath: $TEST_PATH filePath: $AAR_FILE_PATH fileName: $AAR_FILE_NAME"


